Tgupta readme update
OpenLiberty/guide-openliberty-operator-intro pull request #29
Opened 2022-06-08 19:56 UTC by t27gupta

address issue #21

2022-06-13 17:09 UTC, gkwan-ibm requested changes
@t27gupta 
- miss to show the output after `kubectl describe pods`

2022-06-14 17:28 UTC, gkwan-ibm requested changes
@t27gupta 

Improve the statement "Look for an output similar to the following example:" to explain what those for.

e.g. 
> Look for the following output to confirm that the health checks are successfully applied and working:

2022-06-16 08:17 UTC, ramkumar-k-9286 approved these changes

2022-06-16 17:10 UTC, gkwan-ibm approved these changes

2022-06-16 17:10 UTC, merged